title: Research Notebooks
author:
  name: James R.T. Bird & Qingyi 'Moy' Mao
  email: james.bird@manchester.ac.uk


# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Electronic Research Notebooks (ERNs) at Manchester has been set up, in the first instance, to share interative .html plots with researchers and research-supporting staff at the University, which graphically depict features of ERNs.

# Build settings
#Following advice to quote specific git ref (portion following the @) when using remote_theme. This is relevant as the main branch of minima (Minima 3.0) is still in active development. The particular commit is from 27 Feb '25.
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@6.0.0

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

#Added plots folder (with underscore prefix) to the collection of files to be processed by Jekyll.
collections:
  plots:
    output: true #Required to generate resultant page in accordance with front matter.
    permalink: /:collection/:name #Define permalink for the collection of plots rather than globally.

theme_variables:
  # git_host: GitHub
  # back_to_top: true
  # dev-info-banner: false
  # privacy_statement_url: /privacy
  # github_buttons:
    # position: top
    # edit_me: true
    # open_issue: true
    # history: true
  # datatables:
    # searchbuilder: false
    # pagelength: 10
  # headings:
    # related-pages: Related pages
    # more-information-tiles: More information
    # resource-table-all: Tools and resources on this page
    # resource-table-all-collapse: false
  # page_metadata:
    # contributors_sort: true
    # coordinators_sort: true
    # editors_sort: true
    # affiliations_sort: true
  # toc:
    # min_headings: 1
    # headings: 'h2'
  # topnav:
    # theme: light
    # brand_logo: assets/img/main_logo.svg
    # search: true
    # github: true
    # twitter: false
    # bluesky: false
    # linkedin: false
    # fosstodon: false
  # theme_color: 0d6efd
  # fonts:
    # - url towards a font
  # breadcrumb: false

# --- Missing in gitlab: ---
# github:
  # repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
  # source:
    # branch: main
 

